config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  get 'users/:id/follow' => 'users#follow' , as: 'user_follow'
  get 'users/:id/follower' => 'users#follower' , as: 'user_follower'
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'
  get '/search' => 'search#search'
  # resources :relationships, only: [:create, :destroy]
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, class_name: "User", foreign_key: "user_id"
	
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(search)
      if search
        Book.where(['content LIKE ?', "%#{search}%"])
      else
        Book.all
      end
  end

  
  
  
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォロー
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
 # フォロー
 
  attachment :profile_image

  validates :name, presence: true,uniqueness: true,length: {maximum: 20, minimum: 2}
  validates :introduction,length: {maximum: 50}

  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    @user = @book.user
    @book_comment = BookComment.new
  end
  

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
    @user = @book.user
    @book_comment = BookComment.new
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render 'index'
    end
  end

  def edit
     @book = Book.find(params[:id])
      if @book.user == current_user
       render "edit"
      else
      redirect_to books_path
      end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save

  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy

  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def top
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @content)
  end

  private
  def match(model, content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'book'
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{content}%")
    end
  end

  def backward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}")
    end
  end

  def partical(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update]

  def follow
    @user = User.find(params[:id])
    @follows = @user.followings
  end

  def follower
    @user = User.find(params[:id])
    @followers = @user.followers
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book_new = Book.new
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
     render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :email)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#aaa_<%= @book.id %>").html("<%= j(render 'books/comment',  book: @book ) %>");
$("textarea").val("");

app/views/book_comments/destroy.js.erb
$("#aaa_<%= @book.id %>").html("<%= j(render 'books/comment', book: @book ) %>");

app/views/books/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
  <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
  <%= link_to book_comment.user.name , user_path(@user) %>
  <%= book_comment.comment %>
  <% if book_comment.user == current_user %>
  <div class="comment-delete">
    <button type="button" class="btn btn-danger">
    <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), remote: true ,method: :delete %>
    </button>
  </div>
  <% end %>
<% end %>

app/views/books/_favorites.html.erb
  <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete , remote: true do %>
        ♥<%= book.favorites.count %>
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to book_favorites_path(book), method: :post , remote: true do %>
        ♡<%= book.favorites.count %>
      <% end %>
    </p>
  <% end %>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <td id="book_<%= book.id %>">
         <%= render 'books/favorites', book: book %>
        </td>


        <td><%= "コメント数:#{book.book_comments.count} " %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_list.html.erb
 <div class="col-md-3">
   <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <table>
      <tbody>
        <tr></tr>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>

        <li>
          <%= link_to edit_user_path(user.id) do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </li>
      </tbody>
    </table>



      <h2>New book</h2>
      <!-- form_with部分 -->
      <%= form_with model:book, local:true do |f| %>

        <h4>Title</h4>
        <%= f.text_field :title %>

        <h4>Opinion</h4>
        <%= f.text_area :body %>

        <%= f.submit 'Create Book' ,class:"btn-success" %>

      <% end %>
</div>

app/views/books/_table.html.erb
<table class='table'>
  <tr>
    <td><%= link_to user_path(book.user) do %>
      <%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
      <%= book.user.name %>
      <% end %>
    </td>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.body %></td>

    <td id="book_<%= book.id %>">
     <%= render 'books/favorites', book: book %>
    </td>

    <td>コメント数:<%= book.book_comments.count  %></td>

    <% if book.user_id == current_user.id %>
      <td><%= link_to 'Edit', edit_book_path(book), class: "btn btn-sm btn-success edit_book_#{book.id}" %></td>
      <td><%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{book.id}"%></td>
    <% end %>


  </tr>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>
<h1>新規投稿</h1>
<!-- form_with部分 -->
<%= form_with model:@book, local:true do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>

<% end %>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>

      <%= render 'users/info', user: @user %>

      <h2 class="mt-3">New book</h2>

      <%= render 'form', book: @book_new %>

    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		
  	    <div class="table">
  		    <%= render 'books/table', book: @book %>
  	    </div>
    
          <div class="comments">
            
            <div id="aaa_<%= @book.id %>">
             <%= render 'books/comment', book: @book %>
            </div>
            
            <div class="new-comment">
              <%= form_with(model:[@book, @book_comment]) do |f| %>
                <%= f.text_area :comment, cols:'100' ,rows:'10' %>
                <%= f.submit "送信" %>
              <% end %>
            </div>
          </div>
    </div>
  </div>
</div>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %>").html("<%= j(render 'books/favorites',  book: @book ) %>")

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %>").html("<%= j(render 'books/favorites', book: @book ) %>");

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><p><%= "フォロー数: #{ user.followings.count}" %></p></td>
        <td><p><%= "フォロワー数: #{ user.followers.count}" %></p></td>
        <td>
            <% if user_signed_in? %>
              <% if user != current_user %>
                <% if current_user.following?(user) %>
                  <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
                <% else %>
                  <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
                <% end %>
              <% else %>

              <% end %>
            <% end %>
          </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(@user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to @user.followings.count ,  user_follow_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to@user.followers.count , user_follower_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
<% if user == current_user %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% else %>
    <% if user_signed_in? %>
      <% if current_user.following?(@user) %>
          <button type="button" class="btn btn-info">
            <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
          </button>
        <% else %>
          <button type="button" class="btn btn-success">
            <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
          </button>
        <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/follow.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

    <div class='container px-5 px-sm-0'>
        <div class='row'>
          <h2>Follow Users</h2>
          <% unless @follows.empty? %>
            <% @follows.each do |follow| %>
            <tr>
              <td><%= attachment_image_tag(follow, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= follow.email %></td>
              <td><p><%= "フォロー数: #{ follow.followings.count}" %></p></td>
              <td><p><%= "フォロワー数: #{ follow.followers.count}" %></p></td>
              <td><%= link_to 'Show', user_path(follow), class: "user_#{follow.id}" %></td>
            </tr>
            <% end %>
          <% else %>
              <td><%= "このユーザーにフォロワーはいません" %></td>
            </tr>
          <% end %>
        </div>
    </div>
</tbody>
</table>

app/views/users/follower.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

    <div class='container px-5 px-sm-0'>
        <div class='row'>
          <h2>Follow Users</h2>
          <% unless @followers.empty? %>
            <% @followers.each do |follower| %>
            <tr>
              <td><%= attachment_image_tag(follower, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
              <td><%= follower.email %></td>
              <td><p><%= "フォロー数: #{ follower.followings.count}" %></p></td>
              <td><p><%= "フォロワー数: #{ follower.followers.count}" %></p></td>
              <td><%= link_to 'Show', user_path(follower), class: "user_#{follower.id}" %></td>
            </tr>
            <% end %>
          <% else %>
              <td><%= "このユーザーにフォロワーはいません" %></td>
            </tr>
          <% end %>
        </div>
    </div>
</tbody>
</table>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
        <div class='col-md-3'>
            <h2>User info</h2>
            <%= render 'users/info', user: current_user %>
            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>
        </div>
        <div class='col-md-8 offset-md-1'>
            <h2>Users</h2>
            <%= render 'index',users: @users %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>